pub mod args;
pub mod build;
pub mod flags;
pub mod resolve;
pub mod resolved;
pub use build::{detect_build_system, BuildSystem, BuildType};
pub use flags::{BuildFlags, ConfigFlags, ConnectionFlags, MonoRepoFlags, ProfileFlags};
pub use resolved::{ResolvedArgs, ResolvedBuildFlags, ResolvedConnectionFlags, ResolvedMonoFlags};
pub use args::Args;
pub use resolve::{resolve_bool, resolve_with_config};
